// This file is generated

I_note_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tEmily R. Clabbatz<br />\nSocial Security Number: \t199-14-8076<br />\nBirth Date: \t27 Sep 1905<br />\nIssue Year: \tBefore 1951\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tEdith S. Malmstrom<br />\nSocial Security Number: \t084-28-9267<br />\nBirth Date: \t12 Jan 1913<br />\nIssue Year: \t1952-1953<br />\nIssue State: \tNew York<br />\nLast Residence: \t14701, Jamestown, Chautauqua, New York, USA<br />\nDeath Date: \t27 Jul 1996\n</p>\n</div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tEdith Swanson Malmstrom [Edith S Malmstrom] [Edith Swanson Swanson]<br />\nGender: \tFemale<br />\nRace: \tWhite<br />\nBirth Date: \t12 Jan 1913<br />\nBirth Place: \tCorry Erie, Pennsylvania<br />\nDeath Date: \t27 Jul 1996<br />\nFather: \t<br />\nAxel G Swanson<br />\nMother: \t<br />\nEmma W Lawson<br />\nSSN: \t084289267<br />\nNotes: \tJan 1953: Name listed as EDITH SWANSON MALMSTROM; 06 Aug 1996: Name listed as EDITH S MALMSTROM\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nson of Michael Nicholas Rooney<br />\nand Elizabeth Graham;<br />\nhusband of Ruth Irene Bromley\n</p>\n<p>\nJames I Rooney, 89, 213 Wayne St, Corry, died Saturday, Feb 28, 1998, at his home. He was born in Corry, March 22, 1908, son of the late Michael N and Elizabeth Graham Rooney. Mr Rooney worked at the former Aero Supply Co in Corry during World War II. He had also worked for McInnes Steel Manufacturing, the former Canada Lumber Co, and as a contractor in the Corry area. After moving to western New York, he worked for the Williams Lumber Co and the Emerey Lumber Co in French Creek. He retired from the Chautauqua Golf Course in 1972. He was preceded in death in 1980 by his wife of 50 years, Ruth I Bromley Rooney. They were married in Mayville, NY, March 22, 1930. He was also preceded in death by a sister, Mabel Rooney. He is survived by seven daughters, Opal Nichols of Union City, Florence Swanson of Westfield, NY, Ellen Carr, Roberta Rugar, Shirley McCray and her husband Phil, all of Corry, Barbara Rodgers of New Hampshire, and Mabel Smith and her husband Harold, of Sherman, NY; five sons, James E Rooney, Wallace W Rooney and his wife Marcella, all of Corry, Thomas A Rooney of Jamestown, NY, William L Rooney and his wife Marge, of Harmony, NY, and Jerry L Rooney of Steadman, NY; a sister, Margaret R Gates of Corry, and several grandchildren, great-grandchildren, great-great-grandchildren and nieces and nephews. Friends may call at the Bracken Funeral Home in Corry Wednesday from 10 am until the time of a service there at noon. Capt Dennis Smullen of the Salvation Army in Corry will officiate. Burial will be at Pine Grove Cemetery in Corry.<br />\n(Erie Times)\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tMargaret Gates<br />\nSocial Security Number: \t354-14-5961<br />\nBirth Date: \t4 Nov 1911<br />\nIssue Year: \tBefore 1951<br />\nIssue State: \tIllinois\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nCarol E. Hyatt, Corry, Pa., died at her home, Wednesday, April 17, 2014, surrounded by her family and friends. Funeral arrangements are under the care of Bracken Funeral Home, 315 N. Center St., Corry, Pa.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\n&nbsp;\n</p>\n<p>\nName: \tLawrence W Swanson<br />\nGender: \tMale<br />\nRace: \tWhite<br />\nBirth Date: \t27 Apr 1916<br />\nBirth Place: \tCorry Erie, Pennsylvania [Corry Erie|]<br />\nDeath Date: \t22 Mar 1996<br />\nClaim Date: \t28 Apr 1967<br />\nFather: \t<br />\nAxel G Swanson<br />\nMother: \t<br />\nEmma W Lawson<br />\nSSN: \t170186270<br />\nType of Claim: \tEvidence other than birth record submitted; U.S. citizen or alien allowed to work.<br />\nNotes: \t29 Jun 1976: Name listed as LAWRENCE W SWANSON \n</p>\n</div>\n<i class=\"NoteType\">\nGeneral\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tLawrence W. Swanson<br />\nSocial Security Number: \t170-18-6270<br />\nBirth Date: \t27 Apr 1916<br />\nIssue Year: \tBefore 1951<br />\nIssue State: \tPennsylvania<br />\nLast Residence: \t16407, Corry, Erie, Pennsylvania, USA<br />\nDeath Date: \t22 Mar 1996\n</p>\n</div>\n</div>",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tReuben Leonard Swanson<br />\nRace: \tWhite<br />\nAge: \t19<br />\nRelationship to Draftee: \tSelf (Head)<br />\nBirth Date: \t27 Jul 1922<br />\nBirth Place: \tCorry, Pennsylvania, USA<br />\nResidence Place: \tCorry Concord Township, Erie, Pennsylvania, USA<br />\nRegistration Date: \t30 Jun 1942<br />\nRegistration Place: \tCorry Concord Township, Erie, Pennsylvania, USA<br />\nEmployer: \tAxes Swanson<br />\nHeight: \t5 4<br />\nWeight: \t120<br />\nComplexion: \tLight<br />\nHair Color: \tBrown<br />\nEye Color: \tBlue<br />\nNext of Kin: \tEmma Swanson\n</p>\n</div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tReuben L Swanson<br />\nResidence Date: \t1995<br />\nAddress: \t145 Sample Flats Rd<br />\nResidence: \tCorry, PA<br />\nPostal Code: \t16407-3903 \n</p>\n<p>\n&nbsp;\n</p>\n<p>\n&nbsp;\n</p>\n</div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tR. Leonard Swanson<br />\nGender: \tMale<br />\nDeath Age: \t91<br />\nBirth Date: \tabt 1922<br />\nResidence Place: \tSample Flats Rd, Corry, PA<br />\nDeath Date: \t19 Oct 2013<br />\nObituary Date: \t22 Oct 2013\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tVerner E Swanson<br />\nMarital Status: \tSingle, without dependents (Single)<br />\nRank: \tPrivate<br />\nBirth Year: \t1920<br />\nResidence: \tErie, Pennsylvania<br />\nEducation: \t4 years of high school<br />\nCivil Occupation: \tSemiskilled chauffeurs and drivers, bus, taxi, truck, and tractor<br />\nEnlistment Date: \t21 Feb 1942<br />\nEnlistment Place: \tNew Cumberland, Pennsylvania<br />\nService Number: \t33152802<br />\nBranch: \tBranch Immaterial - Warrant Officers, USA<br />\nComponent: \tSelectees (Enlisted Men)<br />\nSource: \tCivil Life<br />\nHeight: \t67<br />\nWeight: \t136 \n</p>\n<p>\n&nbsp;\n</p>\n</div>\n<i class=\"NoteType\">\nPerson Note\n</i>\n<div class=\"grampsstylednote\">\n<p>\nName: \tVerner Swanson<br />\nBirth Date: \t26 Jun 1920<br />\nAddress: \t104 Wayne St<br />\nResidence Place: \tCorry, Pennsylvania, USA<br />\nZip Code: \t16407 \n</p>\n<p>\n&nbsp;\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_note_0.js');
