// This file is generated

I_birth_place_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"Spartansburg, Crawford, Pennsylvania, United States",
"",
"",
"",
"Concord Township, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"",
"Corry, Erie County, Pennsylvania, United States",
"Concord Township, Erie County, Pennsylvania, United States",
"Concord Township, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Concord Township, Erie County, Pennsylvania, United States",
"Philadelphia, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"",
"Spartansburg, Crawford, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"",
"",
"",
"Corry, Erie County, Pennsylvania, United States",
"Erie, Erie County, Pennsylvania, United States",
"",
"Sweden",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"",
"",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"",
"",
"Corry, Erie County, Pennsylvania, United States",
"West Spring Creek, Warren County, Pennsylvania, United States",
"",
"Erie, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry, Erie County, Pennsylvania, United States",
"Corry Memorial Hospital, Corry, Erie County, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"Concord Township, Erie County, Pennsylvania, United States",
"",
"",
"",
"",
"Venango County, Pennsylvania, United States",
"",
"",
"",
"",
"",
"Union City, Erie County, Pennsylvania, United States"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
